// GENERATED by crates/sema/tests/all/common/member_hiding_corpus.rs — do not edit.
// The member-hiding matrix for the Stage 3.3a data-member wake.
namespace HideCorpus
{
    public static class Make
    {
        public static C0 New0() => new C0();
        public static C1 New1() => new C1();
        public static C2 New2() => new C2();
        public static C3 New3() => new C3();
        public static C4 New4() => new C4();
        public static C5 New5() => new C5();
        public static C6 New6() => new C6();
        public static C7 New7() => new C7();
        public static C8 New8() => new C8();
        public static C9 New9() => new C9();
        public static C10 New10() => new C10();
        public static C11 New11() => new C11();
        public static C12 New12() => new C12();
        public static C13 New13() => new C13();
        public static C14 New14() => new C14();
        public static C15 New15() => new C15();
        public static C16 New16() => new C16();
        public static C17 New17() => new C17();
        public static C18 New18() => new C18();
        public static C19 New19() => new C19();
        public static C20 New20() => new C20();
        public static C21 New21() => new C21();
        public static C22 New22() => new C22();
        public static C23 New23() => new C23();
        public static C24 New24() => new C24();
        public static C25 New25() => new C25();
        public static C26 New26() => new C26();
        public static C27 New27() => new C27();
        public static C28 New28() => new C28();
        public static C29 New29() => new C29();
        public static C30 New30() => new C30();
        public static C31 New31() => new C31();
        public static C32 New32() => new C32();
        public static C33 New33() => new C33();
        public static C34 New34() => new C34();
        public static C35 New35() => new C35();
        public static C36 New36() => new C36();
        public static C37 New37() => new C37();
        public static C38 New38() => new C38();
        public static C39 New39() => new C39();
        public static C40 New40() => new C40();
        public static C41 New41() => new C41();
        public static C42 New42() => new C42();
        public static C43 New43() => new C43();
        public static C44 New44() => new C44();
        public static C45 New45() => new C45();
        public static C46 New46() => new C46();
        public static C47 New47() => new C47();
        public static C48 New48() => new C48();
        public static C49 New49() => new C49();
        public static C50 New50() => new C50();
        public static C51 New51() => new C51();
        public static C52 New52() => new C52();
        public static C53 New53() => new C53();
        public static C54 New54() => new C54();
        public static C55 New55() => new C55();
        public static C56 New56() => new C56();
        public static C57 New57() => new C57();
        public static C58 New58() => new C58();
        public static C59 New59() => new C59();
        public static C60 New60() => new C60();
        public static C61 New61() => new C61();
        public static C62 New62() => new C62();
        public static C63 New63() => new C63();
        public static C64 New64() => new C64();
        public static C65 New65() => new C65();
        public static C66 New66() => new C66();
        public static C67 New67() => new C67();
        public static C68 New68() => new C68();
        public static C69 New69() => new C69();
        public static C70 New70() => new C70();
        public static C71 New71() => new C71();
        public static C72 New72() => new C72();
        public static C73 New73() => new C73();
        public static C74 New74() => new C74();
        public static C75 New75() => new C75();
        public static C76 New76() => new C76();
        public static C77 New77() => new C77();
        public static C78 New78() => new C78();
        public static C79 New79() => new C79();
        public static C80 New80() => new C80();
        public static C81 New81() => new C81();
        public static C82 New82() => new C82();
        public static C83 New83() => new C83();
        public static C84 New84() => new C84();
        public static C85 New85() => new C85();
        public static C86 New86() => new C86();
        public static C87 New87() => new C87();
        public static C88 New88() => new C88();
        public static C89 New89() => new C89();
        public static C90 New90() => new C90();
        public static C91 New91() => new C91();
        public static C92 New92() => new C92();
        public static C93 New93() => new C93();
        public static C94 New94() => new C94();
        public static C95 New95() => new C95();
        public static C96 New96() => new C96();
        public static C97 New97() => new C97();
        public static GClosed NewGClosed() => new GClosed();
        public static GOwn NewGOwn() => new GOwn();
        public static DLeaf NewDLeaf() => new DLeaf();
        public static ELeaf NewELeaf() => new ELeaf();
        public static UnrenderableTy NewUnrenderableTy() => new UnrenderableTy();
        public static ImplicitImpl NewImplicitImpl() => new ImplicitImpl();
        public static ExplicitImpl NewExplicitImpl() => new ExplicitImpl();
        public static StructRecv NewStructRecv() => new StructRecv();
        public static BclInherit NewBclInherit() => new BclInherit();
        public static BclHide NewBclHide() => new BclHide();
        public static BclHideStatic NewBclHideStatic() => new BclHideStatic();
        public static IA NullIA() => null;
        public static IB NullIB() => null;
        public static IOwn NullIOwn() => null;
        public static IOne NullIOne() => null;
        public static ITwo NullITwo() => null;
        public static IDeep NullIDeep() => null;
    }

    public class B0
    {
    }

    public class C0 : B0
    {
    }

    public class B1
    {
    }

    public class C1 : B1
    {
        public string P { get; set; }
    }

    public class B2
    {
    }

    public class C2 : B2
    {
        public string P;
    }

    public class B3
    {
    }

    public class C3 : B3
    {
        public string P { set { } }
    }

    public class B4
    {
    }

    public class C4 : B4
    {
        public string P { private get; set; }
    }

    public class B5
    {
    }

    public class C5 : B5
    {
        public static string P { get; set; }
    }

    public class B6
    {
    }

    public class C6 : B6
    {
        public static string P;
    }

    public class B7
    {
    }

    public class C7 : B7
    {
        public string P() => default(string);
    }

    public class B8
    {
    }

    public class C8 : B8
    {
        public string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B9
    {
    }

    public class C9 : B9
    {
        public event System.Action P;
    }

    public class B10
    {
    }

    public class C10 : B10
    {
        internal string P { get; set; }
    }

    public class B11
    {
    }

    public class C11 : B11
    {
        private string P { get; set; }
    }

    public class B12
    {
    }

    public class C12 : B12
    {
        protected string P { get; set; }
    }

    public class B13
    {
    }

    public class C13 : B13
    {
        public class P { }
    }

    public class B14
    {
        public int P { get; set; }
    }

    public class C14 : B14
    {
    }

    public class B15
    {
        public int P { get; set; }
    }

    public class C15 : B15
    {
        public new string P { get; set; }
    }

    public class B16
    {
        public int P { get; set; }
    }

    public class C16 : B16
    {
        public new string P;
    }

    public class B17
    {
        public int P { get; set; }
    }

    public class C17 : B17
    {
        public new string P { set { } }
    }

    public class B18
    {
        public int P { get; set; }
    }

    public class C18 : B18
    {
        public new string P { private get; set; }
    }

    public class B19
    {
        public int P { get; set; }
    }

    public class C19 : B19
    {
        public static new string P { get; set; }
    }

    public class B20
    {
        public int P { get; set; }
    }

    public class C20 : B20
    {
        public static new string P;
    }

    public class B21
    {
        public int P { get; set; }
    }

    public class C21 : B21
    {
        public new string P() => default(string);
    }

    public class B22
    {
        public int P { get; set; }
    }

    public class C22 : B22
    {
        public new string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B23
    {
        public int P { get; set; }
    }

    public class C23 : B23
    {
        public new event System.Action P;
    }

    public class B24
    {
        public int P { get; set; }
    }

    public class C24 : B24
    {
        internal new string P { get; set; }
    }

    public class B25
    {
        public int P { get; set; }
    }

    public class C25 : B25
    {
        private new string P { get; set; }
    }

    public class B26
    {
        public int P { get; set; }
    }

    public class C26 : B26
    {
        protected new string P { get; set; }
    }

    public class B27
    {
        public int P { get; set; }
    }

    public class C27 : B27
    {
        public new class P { }
    }

    public class B28
    {
        public int P;
    }

    public class C28 : B28
    {
    }

    public class B29
    {
        public int P;
    }

    public class C29 : B29
    {
        public new string P { get; set; }
    }

    public class B30
    {
        public int P;
    }

    public class C30 : B30
    {
        public new string P;
    }

    public class B31
    {
        public int P;
    }

    public class C31 : B31
    {
        public new string P { set { } }
    }

    public class B32
    {
        public int P;
    }

    public class C32 : B32
    {
        public new string P { private get; set; }
    }

    public class B33
    {
        public int P;
    }

    public class C33 : B33
    {
        public static new string P { get; set; }
    }

    public class B34
    {
        public int P;
    }

    public class C34 : B34
    {
        public static new string P;
    }

    public class B35
    {
        public int P;
    }

    public class C35 : B35
    {
        public new string P() => default(string);
    }

    public class B36
    {
        public int P;
    }

    public class C36 : B36
    {
        public new string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B37
    {
        public int P;
    }

    public class C37 : B37
    {
        public new event System.Action P;
    }

    public class B38
    {
        public int P;
    }

    public class C38 : B38
    {
        internal new string P { get; set; }
    }

    public class B39
    {
        public int P;
    }

    public class C39 : B39
    {
        private new string P { get; set; }
    }

    public class B40
    {
        public int P;
    }

    public class C40 : B40
    {
        protected new string P { get; set; }
    }

    public class B41
    {
        public int P;
    }

    public class C41 : B41
    {
        public new class P { }
    }

    public class B42
    {
        public static int P { get; set; }
    }

    public class C42 : B42
    {
    }

    public class B43
    {
        public static int P { get; set; }
    }

    public class C43 : B43
    {
        public new string P { get; set; }
    }

    public class B44
    {
        public static int P { get; set; }
    }

    public class C44 : B44
    {
        public new string P;
    }

    public class B45
    {
        public static int P { get; set; }
    }

    public class C45 : B45
    {
        public new string P { set { } }
    }

    public class B46
    {
        public static int P { get; set; }
    }

    public class C46 : B46
    {
        public new string P { private get; set; }
    }

    public class B47
    {
        public static int P { get; set; }
    }

    public class C47 : B47
    {
        public static new string P { get; set; }
    }

    public class B48
    {
        public static int P { get; set; }
    }

    public class C48 : B48
    {
        public static new string P;
    }

    public class B49
    {
        public static int P { get; set; }
    }

    public class C49 : B49
    {
        public new string P() => default(string);
    }

    public class B50
    {
        public static int P { get; set; }
    }

    public class C50 : B50
    {
        public new string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B51
    {
        public static int P { get; set; }
    }

    public class C51 : B51
    {
        public new event System.Action P;
    }

    public class B52
    {
        public static int P { get; set; }
    }

    public class C52 : B52
    {
        internal new string P { get; set; }
    }

    public class B53
    {
        public static int P { get; set; }
    }

    public class C53 : B53
    {
        private new string P { get; set; }
    }

    public class B54
    {
        public static int P { get; set; }
    }

    public class C54 : B54
    {
        protected new string P { get; set; }
    }

    public class B55
    {
        public static int P { get; set; }
    }

    public class C55 : B55
    {
        public new class P { }
    }

    public class B56
    {
        public int P() => default(int);
    }

    public class C56 : B56
    {
    }

    public class B57
    {
        public int P() => default(int);
    }

    public class C57 : B57
    {
        public new string P { get; set; }
    }

    public class B58
    {
        public int P() => default(int);
    }

    public class C58 : B58
    {
        public new string P;
    }

    public class B59
    {
        public int P() => default(int);
    }

    public class C59 : B59
    {
        public new string P { set { } }
    }

    public class B60
    {
        public int P() => default(int);
    }

    public class C60 : B60
    {
        public new string P { private get; set; }
    }

    public class B61
    {
        public int P() => default(int);
    }

    public class C61 : B61
    {
        public static new string P { get; set; }
    }

    public class B62
    {
        public int P() => default(int);
    }

    public class C62 : B62
    {
        public static new string P;
    }

    public class B63
    {
        public int P() => default(int);
    }

    public class C63 : B63
    {
        public new string P() => default(string);
    }

    public class B64
    {
        public int P() => default(int);
    }

    public class C64 : B64
    {
        public new string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B65
    {
        public int P() => default(int);
    }

    public class C65 : B65
    {
        public new event System.Action P;
    }

    public class B66
    {
        public int P() => default(int);
    }

    public class C66 : B66
    {
        internal new string P { get; set; }
    }

    public class B67
    {
        public int P() => default(int);
    }

    public class C67 : B67
    {
        private new string P { get; set; }
    }

    public class B68
    {
        public int P() => default(int);
    }

    public class C68 : B68
    {
        protected new string P { get; set; }
    }

    public class B69
    {
        public int P() => default(int);
    }

    public class C69 : B69
    {
        public new class P { }
    }

    public class B70
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C70 : B70
    {
    }

    public class B71
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C71 : B71
    {
        public new string P { get; set; }
    }

    public class B72
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C72 : B72
    {
        public new string P;
    }

    public class B73
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C73 : B73
    {
        public new string P { set { } }
    }

    public class B74
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C74 : B74
    {
        public new string P { private get; set; }
    }

    public class B75
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C75 : B75
    {
        public static new string P { get; set; }
    }

    public class B76
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C76 : B76
    {
        public static new string P;
    }

    public class B77
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C77 : B77
    {
        public new string P() => default(string);
    }

    public class B78
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C78 : B78
    {
        public new string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B79
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C79 : B79
    {
        public new event System.Action P;
    }

    public class B80
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C80 : B80
    {
        internal new string P { get; set; }
    }

    public class B81
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C81 : B81
    {
        private new string P { get; set; }
    }

    public class B82
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C82 : B82
    {
        protected new string P { get; set; }
    }

    public class B83
    {
        public int P() => default(int);
        public int P(int x) => default(int);
    }

    public class C83 : B83
    {
        public new class P { }
    }

    public class B84
    {
        public event System.Action P;
    }

    public class C84 : B84
    {
    }

    public class B85
    {
        public event System.Action P;
    }

    public class C85 : B85
    {
        public new string P { get; set; }
    }

    public class B86
    {
        public event System.Action P;
    }

    public class C86 : B86
    {
        public new string P;
    }

    public class B87
    {
        public event System.Action P;
    }

    public class C87 : B87
    {
        public new string P { set { } }
    }

    public class B88
    {
        public event System.Action P;
    }

    public class C88 : B88
    {
        public new string P { private get; set; }
    }

    public class B89
    {
        public event System.Action P;
    }

    public class C89 : B89
    {
        public static new string P { get; set; }
    }

    public class B90
    {
        public event System.Action P;
    }

    public class C90 : B90
    {
        public static new string P;
    }

    public class B91
    {
        public event System.Action P;
    }

    public class C91 : B91
    {
        public new string P() => default(string);
    }

    public class B92
    {
        public event System.Action P;
    }

    public class C92 : B92
    {
        public new string P() => default(string);
        public string P(int x) => default(string);
    }

    public class B93
    {
        public event System.Action P;
    }

    public class C93 : B93
    {
        public new event System.Action P;
    }

    public class B94
    {
        public event System.Action P;
    }

    public class C94 : B94
    {
        internal new string P { get; set; }
    }

    public class B95
    {
        public event System.Action P;
    }

    public class C95 : B95
    {
        private new string P { get; set; }
    }

    public class B96
    {
        public event System.Action P;
    }

    public class C96 : B96
    {
        protected new string P { get; set; }
    }

    public class B97
    {
        public event System.Action P;
    }

    public class C97 : B97
    {
        public new class P { }
    }

    public interface IA
    {
        int P { get; }
    }

    public interface IB
    {
        string P { get; }
    }

    public interface IOwn : IA
    {
        new string P { get; }
    }

    public interface IOne : IA
    {
    }

    public interface ITwo : IA, IB
    {
    }

    public interface IDeep : IOne
    {
    }

    public class ImplicitImpl : IA
    {
        public int P => default(int);
    }

    public class ExplicitImpl : IA
    {
        int IA.P => default(int);
    }

    public struct StructRecv
    {
        public int P { get; set; }
    }

    public class GBase<T>
    {
        public T P { get; set; }
    }

    public class GClosed : GBase<int>
    {
    }

    public class GOwn : GBase<int>
    {
        public new string P { get; set; }
    }

    public class DTop
    {
        public int P { get; set; }
    }

    public class DMid : DTop
    {
        public new string P { get; set; }
    }

    public class DLeaf : DMid
    {
    }

    public class ETop
    {
        public int P { get; set; }
    }

    public class EMid : ETop
    {
    }

    public class ELeaf : EMid
    {
    }

    public class UnrenderableTy
    {
        public System.Collections.Generic.List<int> P { get; set; }
    }

    public class BclInherit : System.Exception
    {
    }

    public class BclHide : System.Exception
    {
        public new string HelpLink { get; set; }
    }

    public class BclHideStatic : System.Exception
    {
        public static new string HelpLink { get; set; }
    }

}
